"""initial schema

Revision ID: c99732eb0a66
Revises:
Create Date: 2026-09-28 02:40:34.376214
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c99732eb0a66"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("channel_user_id", sa.String(length=64), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "channel_user_id", name="uq_customer_channel_user"),
    )
    op.create_table(
        "staff_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "STAFF", name="staffrole", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("staff_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_staff_users_username"), ["username"], unique=True)

    op.create_table(
        "conversation_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("step", sa.String(length=32), nullable=False),
        sa.Column("draft_service_type", sa.String(length=64), nullable=True),
        sa.Column("draft_details", sa.Text(), nullable=True),
        sa.Column("draft_phone", sa.String(length=32), nullable=True),
        sa.Column("draft_address", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_states", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_states_customer_id"), ["customer_id"], unique=True
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=24), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("service_type", sa.String(length=64), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "IN_PROGRESS",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_customer_id"), ["customer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_reference"), ["reference"], unique=True)
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)
        batch_op.create_index("ix_orders_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "order_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "IN_PROGRESS",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "IN_PROGRESS",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "actor",
            sa.String(length=64),
            nullable=False,
            comment="Staff username, or 'customer' / 'system'.",
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_events_order_id"), ["order_id"], unique=False)

    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("chat_id", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "FAILED",
                "DEAD",
                name="outboxstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency_key"),
    )
    with op.batch_alter_table("outbox_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outbox_messages_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_outbox_status_next_attempt", ["status", "next_attempt_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_outbox_status_next_attempt")
        batch_op.drop_index(batch_op.f("ix_outbox_messages_status"))

    op.drop_table("outbox_messages")
    with op.batch_alter_table("order_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_events_order_id"))

    op.drop_table("order_events")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_status_created")
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index(batch_op.f("ix_orders_reference"))
        batch_op.drop_index(batch_op.f("ix_orders_customer_id"))

    op.drop_table("orders")
    with op.batch_alter_table("conversation_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_states_customer_id"))

    op.drop_table("conversation_states")
    with op.batch_alter_table("staff_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_staff_users_username"))

    op.drop_table("staff_users")
    op.drop_table("customers")
    # ### end Alembic commands ###
